version: "3.8"
name: 'products-service'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command: [ 'start-dev --import-realm' ]
    networks:
      - new
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    container_name: keycloak
    hostname: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:8080"
  products-db:
    image: postgres:16-alpine
    container_name: products-db
    networks:
      new:
        aliases:
          - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./db/migration:/migrations
    
    command: ["-path", "/migrations/", "-database",  "postgres://postgres:postgres@database:5432/postgres?sslmode=disable", "up", "2"]
    links: 
      - products-db
    depends_on:
      - products-db
networks:
      new:
